Feature/upload to ipfsのプルリクエスト
NII-DG/gogs pull request #4
Opened 2022-03-18 07:59 UTC by ivis-tsukioka

The pull request will be closed without any reasons if it does not satisfy any of following requirements:

1. Please read contributing guidelines:
https://github.com/G-Node/gogs/wiki/Contributing-Code
2. Please describe what your pull request does and which issue you're targeting

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid pull request.**

2022-03-22 01:15 UTC, mistyark requested changes

2022-03-22 01:15 UTC, mistyark commented on custom/conf/app.ini
> +EXTERNAL_URL     = http://192.168.196.160:3000/
public repositoryに公開に、個別サーバの情報を含めないで。
→ドメイン名や社名、個人名はマスクする。

2022-03-22 01:27 UTC, ashikama requested changes

2022-03-22 01:27 UTC, ashikama commented on custom/conf/app.ini
> +RUN_USER   = ivis
パブリックリポジトリなので、社名や個人名、個別サーバの情報を残さないで。
→マスクするなど。

2022-03-23 02:01 UTC, ivis-tsukioka commented on custom/conf/app.ini
> +RUN_USER   = ivis
承知いたしました。
修正します。

2022-03-23 02:04 UTC, ivis-tsukioka commented on custom/conf/app.ini
> +RUN_USER   = ivis
修正しました

2022-03-23 06:12 UTC, ashikama commented on internal/route/repo/view.go
> +	"github.com/ivis-yoshida/gogs/internal/bcapi"
参照元のリポジトリをNII配下のものに変えてください。

2022-03-23 06:38 UTC, ivis-tsukioka commented on internal/route/repo/view.go
> +	"github.com/ivis-yoshida/gogs/internal/bcapi"
修正を加えました

2022-03-23 08:14 UTC, merged