add manual to readme in repository
NII-DG/gogs pull request #75
Opened 2023-05-27 07:17 UTC by ivis-kondoKaho

# PULL REQUEST

## Background

* Explanations were dispersed.
* The manual didn't explain enough.

## Main Points of Modification

* Porting descriptions from the manual
* Added image.
* The added images are imported into the repository.

## Test

* I checked how the added text looks.

![image](https://github.com/NII-DG/gogs/assets/108638856/52ea558d-f4f4-4e20-a1a4-3a15d5c4f16d)

* Confirmed that the image is visible.

![image](https://github.com/NII-DG/gogs/assets/108638856/28ac978a-4379-412a-a6bb-611d0f20b759)

## Viewpoint for Review

* None

## Supplementary Information

* None

## ToDo

* None

2023-05-28 05:33 UTC, ivis-kondoKaho commented
レイアウトを修正。

![image](https://github.com/NII-DG/gogs/assets/108638856/6b530e16-610e-4b45-83e6-827238191258)

2023-05-28 05:45 UTC, ivis-tsukioka requested changes
修正依頼

2023-05-28 05:45 UTC, ivis-tsukioka commented on custom/conf/readme/Default
> +    作成したmaDMPは画面右上にある「View maDMP」から確認できます。
「Dockerfile : 環境構成ファイル」と「作成したmaDMPは画面右上にある「View maDMP」から確認できます。」が一行で表示される。修正依頼

![image](https://github.com/NII-DG/gogs/assets/96706614/74e2deb4-3dd3-40b5-96c2-d21d0ecffbce)

2023-05-28 06:08 UTC, ivis-kondoKaho commented
ボタンの表示制御について

![image](https://github.com/NII-DG/gogs/assets/108638856/a78d8884-e3b2-4f63-b72f-9fecf5d55aa4)

![image](https://github.com/NII-DG/gogs/assets/108638856/31612e2a-ae79-44df-b6a1-7623ba7bac36)

2023-05-28 06:23 UTC, ivis-tsukioka requested changes
課題番号055へのRV
回答お願いします。

2023-05-28 06:23 UTC, ivis-tsukioka commented on custom/conf/readme/Default
対応内容にあった。
『dmpのファイル名やファイルパスを更新しないように注意喚起する。』の文言が見当たりません。
⇒修正もれ、または修正しなくてもよくなった理由は有りますか？

2023-05-28 06:23 UTC, ivis-tsukioka requested changes
課題番号055へのRV
回答お願いします。

2023-05-28 07:47 UTC, ivis-kondoKaho commented on custom/conf/readme/Default
修正漏れなので追記しました。

![image](https://github.com/NII-DG/gogs/assets/108638856/a41ef2c6-becd-47b1-8ab5-467ed0cb285d)

2023-05-28 12:24 UTC, ivis-tsukioka commented
RV OK

2023-05-29 04:18 UTC, ivis-kondoKaho commented
構築時にエラーになった際の案内について決める必要あり。

2023-05-29 04:33 UTC, ivis-kondoKaho commented
> 構築時にエラーになった際の案内について決める必要あり。

![image](https://github.com/NII-DG/gogs/assets/108638856/ad10cf83-c1a8-404d-9200-508029e168a0)

2023-05-29 04:39 UTC, ivis-kondoKaho commented
以下のように記述を修正。

![image](https://github.com/NII-DG/gogs/assets/108638856/73d9c858-a02b-416a-a9cc-ac0f65f097ed)

2023-05-29 09:48 UTC, merged